stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://fandom-nft-marketplace.netlify.app
  only:
    - dev
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod