default:
  image: node:18-buster

before_script:
    - npm install
    - npm install -g netlify-cli --unsafe-perm=true
    - npm run build

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://fandom-nft-marketplace.netlify.app
  only:
    - dev
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir public/ --prod