image: node:17-alpine3.14

variables:
  NETLIFY_SITE_ID: $NETLIFY_SITE_ID
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - npm install netlify-cli --save-dev
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir public/ --prod