image: node:18

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - npm install
    - npm install netlify-cli --save-dev
    - npm run build
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir public/
  only:
    - dev
