# name: Deploy prod

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - hedera-testnet

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - name: Install Netlify CLI
#         run: npm install -g netlify-cli

#       - name: Print values
#         # run: |
#         #  echo "Repo: ${{ github.repository }}"
#         #  echo "${{ github.repository_owner }}"
#         #  echo "$NETLIFY_AUTH_TOKEN"
#         #  echo "$NETLIFY_SITE_ID"
#         if: env.NETLIFY_AUTH_TOKEN == 'zvdeOZ-g3SGylrmyq4vaGkT-K9bK9q1ckY6JhwkGdo8'
#         run: echo "I know what the secret token is!"
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

#       - name: Print Value if not equal
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         if: env.NETLIFY_AUTH_TOKEN != 'zvdeOZ-g3SGylrmyq4vaGkT-K9bK9q1ckY6JhwkGdo8'
#         run: echo "I don't know what the secret token is!"

#       - name: Print
#         env: 
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#         run: |
#          echo "$NETLIFY_AUTH_TOKEN"
       
#       # - name: Install deps
#       #   run: npm install
#       # - name: Deploy
#       #   run: REACT_APP_PINATA_SECRET_KEY=${{secrets.REACT_APP_PINATA_SECRET_KEY}} REACT_APP_PINATA_API_KEY=${{secrets.REACT_APP_PINATA_API_KEY}} CI=false npm run build
#       # - name: Deploy to netlify
#       #   uses: netlify/actions/cli@master
#       #   env:
#       #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#       #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#       #     REACT_APP_PINATA_SECRET_KEY: ${{ secrets.REACT_APP_PINATA_SECRET_KEY }}
#       #     REACT_APP_PINATA_API_KEY: ${{ secrets.REACT_APP_PINATA_API_KEY }}
#       #   with:
#       #     args: deploy --dir=build --prod
#       #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'


name: Development workflow

on:
  push:
    branches:
      - hedera-testnet

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: CI=false npm run build --if-present

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'