name: Deploy prod

on:
  workflow_dispatch:
  push:
    branches:
      - hedera-testnet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Print values 
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # run: |
        #  echo "Repo: ${{ github.repository }}" 
        #  echo "${{ github.repository_owner }}"
        #  echo "$NETLIFY_AUTH_TOKEN"
        #  echo "$NETLIFY_SITE_ID"
        if:  NETLIFY_AUTH_TOKEN == 'zvdeOZ-g3SGylrmyq4vaGkT-K9bK9q1ckY6JhwkGdo8'
        run: echo "I know what the secret token is!"

      - name: Print Value if equal
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        if: env.NETLIFY_AUTH_TOKEN == 'zvdeOZ-g3SGylrmyq4vaGkT-K9bK9q1ckY6JhwkGdo8'
        run: echo "I don't know what the secret token is!"

        
      - name: Print Value if not equal
        env: 
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        if: NETLIFY_AUTH_TOKEN != 'zvdeOZ-g3SGylrmyq4vaGkT-K9bK9q1ckY6JhwkGdo8'
        run: echo "I don't know what the secret token is!"

      # - name: Install deps
      #   run: npm install
      # - name: Deploy
      #   run: REACT_APP_PINATA_SECRET_KEY=${{secrets.REACT_APP_PINATA_SECRET_KEY}} REACT_APP_PINATA_API_KEY=${{secrets.REACT_APP_PINATA_API_KEY}} CI=false npm run build
      # - name: Deploy to netlify
      #   uses: netlify/actions/cli@master
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     REACT_APP_PINATA_SECRET_KEY: ${{ secrets.REACT_APP_PINATA_SECRET_KEY }}
      #     REACT_APP_PINATA_API_KEY: ${{ secrets.REACT_APP_PINATA_API_KEY }}

      #   with:
      #     args: deploy --dir=build --prod
      #     secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'


        
